# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('blog', '0002_auto_20170509_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Header image displayed when rendering the article or if the article is featured on the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Default header image used if the featured article does not provide any header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
    ]
