version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.63
    - 1.17.0
    - 1.17.1
    - 1.17.10
    - 1.17.13
    - 1.17.14
    - 1.17.15
    - 1.17.17
    - 1.17.18
    - 1.17.19
    - 1.17.20
    - 1.17.22
    - 1.17.23
    - 1.17.24
    - 1.17.25
    - 1.17.27
    - 1.17.28
    - 1.17.29
    - 1.17.30
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.39
    - 1.17.4
    - 1.17.40
    - 1.17.41
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.49
    - 1.17.5
    - 1.17.50
    - 1.17.51
    - 1.17.52
    - 1.17.54
    - 1.17.55
    - 1.17.58
    - 1.17.6
    - 1.17.8
    - 1.17.9
  - dependency-name: faker
    versions:
    - 6.5.2
    - 6.6.1
  - dependency-name: wagtail
    versions:
    - 2.12.1
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.2
