dist: xenial

language: python

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

before_install:
  - nvm install 11.1.0
  - nvm use 11.1.0
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

install:
  - pip install pipenv
  - pip install --upgrade setuptools
  - pipenv install --dev
  - npm install --dev
  - cp tests/.env.json.ci .env.json

before_script:
  - psql -c 'create database ci;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres

script:
  - make qa
  - make coverage
