# Generated by Django 2.2.1 on 2019-05-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpage_header_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredientssection',
            options={'ordering': ['sort_order'], 'verbose_name': 'Recipe ingredients section', 'verbose_name_plural': 'Recipe ingredients sections'},
        ),
        migrations.AlterModelOptions(
            name='recipeinstructionssection',
            options={'ordering': ['sort_order'], 'verbose_name': 'Recipe instructions section', 'verbose_name_plural': 'Recipe instructions sections'},
        ),
    ]
