# Generated by Django 2.1.7 on 2019-03-25 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_simplepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='header_image',
            field=models.ForeignKey(help_text='Header image displayed when rendering the article or if the article is featured on the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='header_image',
            field=models.ForeignKey(help_text='Header image displayed when rendering the article or if the article is featured on the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='header_image',
            field=models.ForeignKey(help_text='Header image displayed when rendering the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
    ]
