# Generated by Django 2.2.1 on 2019-05-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190511_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='noindex',
            field=models.BooleanField(default=False, verbose_name='Disable robots indexation'),
        ),
    ]
