# Generated by Django 2.2.4 on 2019-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_simplepage_noindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='cook_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Cook time'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='fridge_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Fridge time'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='preparation_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Preparation time'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='rest_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Rest time'),
        ),
    ]
