# Generated by Django 2.2.4 on 2019-09-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190904_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='categories',
        ),
    ]
