# Generated by Django 2.2.4 on 2019-09-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190905_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryarticlepage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryarticlepage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='categoryrecipepage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryrecipepage',
            name='page',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryArticlePage',
        ),
        migrations.DeleteModel(
            name='CategoryRecipePage',
        ),
    ]
