# Generated by Django 2.2.4 on 2019-09-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190905_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='header_image',
            field=models.ForeignKey(help_text='Header image displayed when rendering the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='header_image',
            field=models.ForeignKey(help_text='Header image displayed when rendering the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
    ]
