# Generated by Django 2.2.5 on 2019-09-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190905_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagrecipepage',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='tagrecipepage',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='show_tags',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TagArticlePage',
        ),
        migrations.DeleteModel(
            name='TagRecipePage',
        ),
    ]
