# Generated by Django 2.2.7 on 2019-11-25 02:10

from django.db import migrations, models
import main.common.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190922_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='seasons',
            field=main.common.db.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn')], max_length=6), default=list, size=4, verbose_name='Seasons'),
        ),
    ]
