# Generated by Django 2.2.7 on 2019-11-25 02:14

from django.db import migrations


def backfill_recipe_seasons(apps, schema_editor):
    RecipePage = apps.get_model('blog', 'RecipePage')
    RecipePage.objects.update(seasons=['winter', 'spring', 'summer', 'autumn'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_recipepage_seasons'),
    ]

    operations = [
        migrations.RunPython(backfill_recipe_seasons, reverse_code=migrations.RunPython.noop),
    ]
