# Generated by Django 2.2.7 on 2019-12-09 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0014_auto_20191124_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='recipe_image',
            field=models.ForeignKey(blank=True, help_text='Recipe image displayed in the recipe sheet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Recipe image'),
        ),
    ]
