# Generated by Django 3.1.2 on 2020-11-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200112_2143'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION unaccent'),
        migrations.RunSQL('CREATE TEXT SEARCH CONFIGURATION nb_french ( COPY = french )'),
        migrations.RunSQL(
            'ALTER TEXT SEARCH CONFIGURATION nb_french '
            'ALTER MAPPING FOR hword, hword_part, word '
            'WITH unaccent, french_stem'
        ),
    ]
