# Generated by Django 5.0.14 on 2025-12-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201107_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipepage',
            options={'ordering': ['title'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='simplepage',
            options={'ordering': ['title'], 'verbose_name': 'Simple page', 'verbose_name_plural': 'Simple pages'},
        ),
    ]
