name: CI - Python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pip poetry
        poetry install
        poetry run pip install -U "${{ matrix.django-version }}"
    - name: Run QA checks
      run: |
        make lint_python
        make isort_python
    - name: Run tests suite
      run: poetry run pytest --cov-report xml --cov precise_bbcode
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        yml: ./.codecov.yml
        fail_ci_if_error: true
