name: CI - Python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: ci
        ports:
        - 5432:5432
        # Needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install PostgreSQL client
      run: sudo apt-get -yqq install libpq-dev
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pip poetry
        poetry install
        poetry run pip install -U "${{ matrix.django-version }}"
    - name: Run QA checks
      run: |
        make lint_python
        make isort_python
    - name: Run tests suite
      run: poetry run pytest --cov-report xml --cov precise_bbcode
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        yml: ./.codecov.yml
        fail_ci_if_error: true
